-- Migration 001: Supabase schema already contains all tables.
-- This file is kept for reference only.
-- The actual schema is managed in Supabase dashboard.
--
-- Tables in use:
--   users, customer_profiles, body_measurements, customer_photos
--   shops, shop_services, shop_specialties
--   shop_fabrics, shop_fabric_images, fabric_tags, fabric_uploads
--   weave_patterns, weave_color_variants
--   base_styles, design_briefs, generated_designs, tryon_results
--   orders, order_status_logs
--   weaving_orders, weaving_order_status_logs
--   shipments, shipment_status_logs, payments
--   notifications, community_posts, post_images, post_likes
--   shop_reviews, fabric_origins
--
-- To seed a test admin account run:
--   INSERT INTO users (email, display_name, password_hash, role)
--   VALUES ('laya.thailand@gmail.com
-- ', 'Admin LAYA',
--     '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4tbQHX3qK6', 'admin')
--   ON CONFLICT (email) DO NOTHING;
--   (password = Admin@1234)
